apiVersion: serving.knative.dev/v1
kind: Service
metadata:
      name: my-service
      annotations:
        run.googleapis.com/ingress: internal
        run.googleapis.com/cpu-throttling: 'False'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '2'
        autoscaling.knative.dev/maxScale: '50'
    spec:
      containers:
      - image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi